---
project_name: go-rtm2http-slackbot

release:
  github:
    owner: nikepan
    name: go-rtm2http-slackbot

builds:
  - binary: go-rtm2http-slackbot
    goos: &goos
      - darwin
      - windows
      - linux
    goarch: &goarch
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    main: ./
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - config.sample.json
      - README.md
      - LICENSE
